export const USER_CHECK_AUTH_START   = 'USER_CHECK_AUTH_START'
export const USER_CHECK_AUTH_SUCCESS = 'USER_CHECK_AUTH_SUCCESS'
export const USER_CHECK_AUTH_FAILED  = 'USER_CHECK_AUTH_FAILED'

export const USER_SIGN_OUT_START   = 'USER_SIGN_OUT_START'
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS'
export const USER_SIGN_OUT_FAILED  = 'USER_SIGN_OUT_FAILED'

export const USER_SIGN_IN_START   = 'USER_SIGN_IN_START'
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const USER_SIGN_IN_FAILED  = 'USER_SIGN_IN_FAILED'